# -*- coding: utf-8 -*-
"""south-america-co2-eda_Viz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m71FrynvBfxAjNJXsGaz1iB5IcLfz_KC

#**1. Dataset Overview**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

clean_data_url = "https://raw.githubusercontent.com/dsaedinia/DSE511-HW2/main/data/clean/south_america_co2_data.csv"

df = pd.read_csv(clean_data_url)

df.head()

"""#**2. Data Quality Check**"""

# Shape
print("Shape:", df.shape)

# Column names
print("\nColumns:")
print(df.columns.tolist())

# Data types
print("\nData types:")
print(df.dtypes)

# Basic information
print("\nDataset information:")
df.info()

# Summary statistics
print("\nSummary statistics:")
display(df.describe(include="all"))

print("Shape:", df.shape)
print("Number of countries:", df["country"].nunique())
print("Year range:", df["year"].min(), "to", df["year"].max())

# Check missing values
print("Missing values:")
display(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

# First 10 rows
display(df.head(10))

missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": df.isnull().mean() * 100
})

missing[missing["Missing Count"] > 0]

df[df["gdp"].isna()][["country", "year", "gdp"]]

df.groupby("country")["gdp"].apply(lambda x: x.isna().sum())

df[df["country"] == "Venezuela"][
    ["year", "gdp", "co2_per_gdp", "energy_per_gdp"]
].head()

df[df["country"] == "Venezuela"][
    ["gdp", "co2_per_gdp", "energy_per_gdp"]
].isna().sum()

country_year_summary = (
    df.groupby("country")["year"]
      .agg(["min", "max", "count"])
      .sort_index()
)

country_year_summary

print(
    "Duplicate country-year observations:",
    df[["country", "year"]].duplicated().sum()
)

print(
    "Duplicate complete rows:",
    df.duplicated().sum()
)

"""#**3. Univariate Analysis**"""

df.describe().T

"""### 3.1 CO₂ emissions"""

plt.figure(figsize=(8, 5))

plt.hist(df["co2"], bins=30, edgecolor="black")

plt.xlabel("CO₂ emissions (Mt)")
plt.ylabel("Number of observations")
plt.title("Distribution of Annual CO₂ Emissions")

plt.show()

"""### 3.2 CO₂ per capita"""

plt.figure(figsize=(8, 5))

plt.hist(df["co2_per_capita"], bins=30, edgecolor="black")

plt.xlabel("CO₂ emissions per capita")
plt.ylabel("Number of observations")
plt.title("Distribution of CO₂ Emissions per Capita")

plt.show()

"""### 3.3 GDP"""

print("Descriptive statistics for GDP:")
display(df['gdp'].describe())

plt.figure(figsize=(10, 6))
plt.hist(df['gdp'].dropna(), bins=30, edgecolor='black')
plt.xlabel('GDP')
plt.ylabel('Number of observations')
plt.title('Distribution of GDP')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""### 3.4 Primary energy consumption"""

print("Descriptive statistics for Primary Energy Consumption:")
display(df['primary_energy_consumption'].describe())

plt.figure(figsize=(10, 6))
plt.hist(df['primary_energy_consumption'].dropna(), bins=30, edgecolor='black')
plt.xlabel('Primary Energy Consumption')
plt.ylabel('Number of observations')
plt.title('Distribution of Primary Energy Consumption')
plt.grid(axis='y', alpha=0.75)
plt.show()

"""# 4. Country Comparisons

### 4.1 Total CO₂ by country
"""

country_co2_pc = (
    df.groupby("country")["co2_per_capita"]
      .mean()
      .sort_values(ascending=False)
)

country_co2_pc

"""### 4.2 CO₂ per capita by country"""

country_co2_pc = df.groupby('country')['co2_per_capita'].mean()
display(country_co2_pc)

plt.figure(figsize=(10, 6))

country_co2_pc.sort_values().plot(kind="barh")

plt.xlabel("Average CO₂ emissions per capita")
plt.ylabel("Country")
plt.title("Average CO₂ Emissions per Capita by Country")

plt.show()

"""# 5. Temporal Analysis

### 5.1 CO₂ trends, 1990–2024
"""

co2_trend = df.groupby('year')['co2'].sum()

plt.figure(figsize=(12, 6))
co2_trend.plot(kind='line', marker='o', linestyle='-')
plt.xlabel('Year')
plt.ylabel('Total CO₂ Emissions (Mt)')
plt.title('Total CO₂ Emissions Trend in South America (1990-2024)')
plt.grid(True)
plt.show()

"""# 6. Bivariate Analysis

### 6.1 GDP vs CO₂
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='gdp', y='co2', alpha=0.6)
plt.xlabel('GDP')
plt.ylabel('CO₂ Emissions (Mt)')
plt.title('GDP vs. CO₂ Emissions in South America')
plt.grid(True)
plt.show()

"""### 6.2 Bivariate Analysis: Population vs CO₂"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='population', y='co2', alpha=0.6)
plt.xlabel('Population')
plt.ylabel('CO₂ Emissions (Mt)')
plt.title('Population vs. CO₂ Emissions in South America')
plt.grid(True)
plt.show()

"""### 6.3 Bivariate Analysis: Energy Consumption vs CO₂"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='primary_energy_consumption', y='co2', alpha=0.6)
plt.xlabel('Primary Energy Consumption')
plt.ylabel('CO₂ Emissions (Mt)')
plt.title('Primary Energy Consumption vs. CO₂ Emissions in South America')
plt.grid(True)
plt.show()

"""# 7. Correlation Analysis"""

df.corr(numeric_only=True)

import seaborn as sns

plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Variables')
plt.show()

"""## 8. Key Findings

## Key Findings from EDA

### 1. Large Differences in Total CO₂ Emissions Across Countries

The analysis shows substantial differences in total CO₂ emissions among South American countries. **Brazil has the highest average annual CO₂ emissions, at approximately 391.59 Mt**, followed by Argentina (**160.16 Mt**) and Venezuela (**138.22 Mt**). In contrast, Guyana and Suriname have considerably lower total emissions. This indicates that total regional CO₂ emissions are concentrated among a relatively small number of countries with larger populations and greater levels of economic and energy activity.

### 2. Total CO₂ Emissions and CO₂ per Capita Show Different Patterns

Brazil has the highest total CO₂ emissions, but it does not have the highest average CO₂ emissions per capita. **Venezuela and Suriname have the highest average CO₂ emissions per capita, at approximately 5.26 and 4.34 tonnes per person, respectively.** This demonstrates that total emissions and per-capita emissions capture different aspects of environmental impact. A country with a smaller population can have relatively low total emissions while still having high emissions per person.

### 3. CO₂ Emissions Are Strongly Right-Skewed

The distribution of annual CO₂ emissions is strongly **right-skewed**. Most country-year observations have relatively low emissions, with many observations below approximately 100 Mt, while a smaller number of observations have substantially higher emissions, including values above 500 Mt. This indicates considerable variation in emissions across countries and years. Because of this skewed distribution, the median can provide a useful representation of a typical observation in addition to the mean.

### 4. GDP, Population, Energy Consumption, and CO₂ Are Strongly Associated

The correlation analysis reveals very strong positive relationships among population, economic activity, energy consumption, and total CO₂ emissions. Some of the strongest correlations are:

| Relationship                       | Correlation (r) |
| ---------------------------------- | --------------: |
| GDP and CO₂                        |       **0.993** |
| GDP and Primary Energy Consumption |       **0.997** |
| CO₂ and Primary Energy Consumption |       **0.990** |
| Population and CO₂                 |       **0.939** |
| Population and GDP                 |       **0.976** |

These results indicate that observations with larger populations, higher GDP, and greater primary energy consumption tend to have higher total CO₂ emissions. However, these correlations represent **associations and do not establish causal relationships**.

### 5. Per-Capita Measures Provide a Different Perspective

Although total CO₂ emissions are strongly associated with GDP and population, **CO₂ per capita has a much weaker relationship with these variables**. The correlation between CO₂ per capita and GDP is only **0.056**, while its correlation with population is **−0.066**. This contrast shows that analyzing only total emissions can hide important differences in emissions intensity at the individual level. Therefore, both total and per-capita measures are important for understanding emissions patterns.

### 6. Emissions Intensity Is Related to Energy Intensity

The correlation between **CO₂ per GDP and energy per GDP is 0.708**, indicating a relatively strong positive association between emissions intensity and energy intensity. This suggests that observations with higher energy use relative to GDP also tend to have higher CO₂ emissions relative to GDP. Measures of emissions and energy intensity therefore provide additional information beyond total emissions.

### 7. Missing GDP Data for Venezuela Is an Important Limitation

A significant data-quality limitation is the absence of GDP-related information for **Venezuela across the 1990–2024 period**. The variables `gdp`, `co2_per_gdp`, and `energy_per_gdp` contain missing values for Venezuela. Consequently, analyses involving these economic indicators may not fully represent all countries in the dataset. This limitation should be considered when interpreting GDP-related comparisons and correlations.

### Overall Finding

Overall, the EDA shows that **total CO₂ emissions are strongly associated with population size, GDP, and primary energy consumption**, while per-capita and intensity-based measures reveal different patterns across countries. The substantial differences between countries, the right-skewed distribution of emissions, and the strong correlations among economic and energy variables demonstrate the importance of examining emissions from multiple perspectives rather than relying on total CO₂ alone.
"""